repos:
    # Standard Checks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-toml
          - id: debug-statements
    # Python
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.8.2
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.37.3
      hooks:
          - id: pyupgrade
            args: [--py3-plus, --py38-plus]
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
            language_version: python3
    - repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
            additional_dependencies: [flake8-bugbear==22.10.27, flake8-bandit==4.1.1, flake8-builtins==2.0.1, flake8-local-import==1.0.6]
