apiVersion: v1
kind: Service
metadata:
  name: ${GATEWAY_APP_NAME}
spec:
  selector:
    app: ${GATEWAY_APP_NAME}
  type: ClusterIP
  ports:
    - port: ${PORT_GATEWAY}
      targetPort: ${PORT_GATEWAY}
      protocol: TCP
