apiVersion: v1
kind: Service
metadata:
  name: ${AUTH_APP_NAME}
spec:
  selector:
    app: ${AUTH_APP_NAME}
  type: ClusterIP
  ports:
    - port: ${PORT_AUTH}
      targetPort: ${PORT_AUTH}
      protocol: TCP
