apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${RABBITMQ_APP_NAME}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
